{% set data = load_setup_py_data() %}

package:
  name: cpacs2to3
  version: {{ data.get('version') }}

source:
  git_url: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 3) }}
  noarch: python
  entry_points:
    - cpacs2to3 = cpacs2to3.cpacs_converter:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - tigl3
    - tigl >=2.2.3
    - tixi >=2.2.4
    - tixi3 >=3.0.3
    - numpy
    - semver

test:
  imports:
    - cpacs2to3

  commands:
    - cpacs2to3 --help

about:
  home:  https://github.com/DLR-SC/cpacs2to3
  license: Apache 2.0
