sudo: false

language: minimal

git:
  depth: false

jobs:
  include:
    - stage: test

      before_install:
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
          else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
          fi;
        - chmod +x miniconda.sh
        - yes | ./miniconda.sh -b -p $HOME/miniconda
        - export PYTHONUNBUFFERED=1
        - export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda config --add channels https://conda.anaconda.org/dlr-sc
        - source $HOME/miniconda/etc/profile.d/conda.sh

        - conda create -n cpacs2to3_devel python=3.5 tigl3 tigl tixi3 tixi numpy semver pytest
        - conda activate cpacs2to3_devel

      install: pip install -e . --user

      script: pytest

    - stage: deploy

      before_install:
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
          else
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
          fi;
        - chmod +x miniconda.sh
        - yes | ./miniconda.sh -b -p $HOME/miniconda
        - export PYTHONUNBUFFERED=1
        - export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda install conda-build gitpython anaconda-client
        - conda config --add channels https://conda.anaconda.org/dlr-sc
        - conda config --add channels https://conda.anaconda.org/dlr-sc/label/tigl-dev

      script:
        - if [ -n "$ANACONDA_API_TOKEN" ]; then
            conda build ci/conda --user DLR-SC --token $ANACONDA_API_TOKEN
          else
            conda build ci/conda
          fi
